<?php

/**
 * @file
 * Variables for various options used in theme settings form.
 */

// Site flavors
$site_flavor_options = array(
  'blue-diamonds' => t('Blue Diamonds'),
  'purple-horseshoes' => t('Purple Horseshoes'),
  'green-clovers' => t('Green Clovers'),
);

// Company divisions
$company_division_options = array(
  0 => t('Leprechaun Arbitration'),
  1 => t('Sugar Procurement'),
  2 => t('Marshmallow Engineering'),
);

// Territories
$territory_options = array(
  0 => t('NE United States'),
  1 => t('SE United States'),
  2 => t('SW United States'),
);

// Leprechaun mascots
$leprechaun_mascot_options = array(
  'smiley' => t('Smiley McSmiles'),
  'surly' => t('Surly O\'Crabby'),
  'tipsy' => t('Tipsy McSauced'),
);